### ISSUE TITLE
Example crash

### ISSUE THREAD

**Issue by Gehim** [AndreMiras/pycaw#1]
i got this crash:

```
Exception ignored in: <bound method _compointer_base.__del__ of <POINTER(IAudioSessionControl) ptr=0x1437608 at 383e080>>
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 916, in __del__
    self.Release()
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 1170, in Release
    return self.__com_Release()
OSError: [WinError -1073741795] Windows Error 0xc000001d
Exception ignored in: <bound method _compointer_base.__del__ of <POINTER(IAudioSessionControl) ptr=0x2ec5da0 at 383e3a0>>
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 916, in __del__
    self.Release()
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 1170, in Release
    return self.__com_Release()
OSError: [WinError -1073741795] Windows Error 0xc000001d
Exception ignored in: <bound method _compointer_base.__del__ of <POINTER(IAudioSessionControl) ptr=0x8dc040 at 3bc42b0>>
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 916, in __del__
    self.Release()
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 1170, in Release
    return self.__com_Release()
OSError: [WinError -1073741795] Windows Error 0xc000001d
Exception ignored in: <bound method _compointer_base.__del__ of <POINTER(IAudioSessionControl) ptr=0x13e0260 at 3bc4350>>
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 916, in __del__
    self.Release()
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 1170, in Release
    return self.__com_Release()
OSError: exception: access violation writing 0x004E0049
Exception ignored in: <bound method _compointer_base.__del__ of <POINTER(IAudioSessionControl) ptr=0x34a4860 at 3bc43f0>>
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 916, in __del__
    self.Release()
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 1170, in Release
    return self.__com_Release()
OSError: exception: access violation writing 0xAA000000
Exception ignored in: <bound method _compointer_base.__del__ of <POINTER(IAudioSessionControl) ptr=0x34a4928 at 3bc4490>>
Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 916, in __del__
    self.Release()
  File "C:\Python35\lib\site-packages\comtypes\__init__.py", line 1170, in Release
    return self.__com_Release()
OSError: exception: access violation writing 0x00770077
```

When i try to set the volume for firefox a few times in a row.
Hope you can help me,
Regards

**Comment by AndreMiras** [comment]
Can you attach a simple script that reproduces the issue? Otherwise it's very difficult to take a look.
Also you're supposed to give a little bit more regarding your environment such as:
- current requirements (pip freeze)
- OS version
- architecture
- Python version
- pycaw version
- and so on

**Comment by Gehim** [comment]
Working on Windows 10-64 bit with Python 3.5.2 32 bit.
Pycaw version:

> Metadata-Version: 1.0
> Name: pycaw
> Version: 20160508

pip freeze:

> cffi==1.8.2
> comtypes==1.1.2
> cryptography==1.5
> cycler==0.10.0
> enum34==1.1.6
> flake8==3.0.4
> idna==2.1
> inflection==0.3.1
> matplotlib==1.5.2
> mccabe==0.5.2
> more-itertools==2.2
> ndg-httpsclient==0.4.2
> numpy==1.11.1
> pandas==0.18.1
> Pillow==3.3.1
> pocketsphinx==0.1.3
> psutil==4.3.1
> pyasn1==0.1.9
> PyAudio==0.2.9
> pycaw==20160508
> pycodestyle==2.0.0
> pycparser==2.14
> pyflakes==1.2.3
> PyMySQL==0.7.9
> pyOpenSSL==16.1.0
> pyparsing==2.1.8
> python-dateutil==2.5.3
> pyttsx==1.1
> pytz==2016.6.1
> pywin32==220
> Quandl==3.0.1
> requests==2.11.1
> scikit-learn==0.17.1
> six==1.10.0
> sklearn==0.0
> speech==0.5.2
> SpeechRecognition==3.4.6
> WMI==1.4.9

Python crashs with following code:
```
from pycaw.pycaw import AudioUtilities
def change_mute_process(process_list=(), mute=1):
    sessions = AudioUtilities.GetAllSessions()
    for session in sessions:
        if session.Process and session.Process.name() in process_list:
            volume = session.SimpleAudioVolume
            volume.SetMute(mute, None)
for x in range(0,100):
    change_mute_process(("firefox.exe",),0)
```

The last for loop is for testing purpose only, because sometimes it crashs and sometimes don't. Usually after 2-5 iterations.

**Comment by AndreMiras** [comment]
Thanks, this is a lot better.
I could indeed reproduce with this exact setup:

- Windows 10 64 bits
- Python 3.5.2 32 bits installed with `choco install python3-x86_32`
- pycaw==20160508
- comtypes==1.1.2
- enum34==1.1.6
- psutil==4.3.1

Also I didn't see this issue on Windows 7 32 bits and Python2.7 and I don't think I saw it with Python 3.5 64 bits on Windows 10 64 bits.
It needs more investigations, but at least I can reproduce.

**Comment by AndreMiras** [comment]
Also on my situation, it crashes after 50 calls, so I had to modify your loop and the error sometimes varies, like below:
```
Traceback (most recent call last):
  File "crash.py", line 13, in <module>
    change_mute_process(("firefox.exe",),0)
  File "crash.py", line 8, in change_mute_process
    if session.Process and session.Process.name() in process_list:
  File "C:\Users\andre_000\Documents\Visual Studio 2010\Projects\pycaw\pycaw\pycaw.py", line 546, in Process
    if self._process is None and self.ProcessId != 0:
  File "C:\Users\andre_000\Documents\Visual Studio 2010\Projects\pycaw\pycaw\pycaw.py", line 556, in ProcessId
    return self._ctl.GetProcessId()
OSError: exception: access violation writing 0x00000014
```

**Comment by AndreMiras** [comment]
OK, I think I've found the root cause, but I'm not sure about the fix.
https://github.com/enthought/comtypes/issues/17

**Comment by AndreMiras** [comment]
OK as usual it took a lot of time to understand what was really going on, but the fix is only two lines of code (plus unit tests). See 8a176de0061309dd2d8f92b3ac99900003a31904 to get the details.
Could you please install from the develop branch and tell me if it fixes it for you.
`pip install https://github.com/AndreMiras/pycaw/archive/develop.zip`
Also you will probably need to update your requirements since I've added a dependency to `future`.
If it's all good I'll make a new release.

**Comment by Gehim** [comment]
I honestly have no clue what you did, but after I reinstalled it, it works fine 💃 
Thank you very very much dude 💃  Great work, fast respond !
I will mention you somewhere in my code for sure!
Regards,

**Comment by AndreMiras** [comment]
Glad it works :) I've tagged a new 20160929 release.

**Comment by LeNarvalo** [comment]
Same bug with your fixs =(
But the bug doesn't crash my script, so...

**Comment by KillerBOSS2019** [comment]
I get this same error on latest version for some reason
