### ISSUE TITLE
Using the IAudioEndpointVolumeCallback::OnNotify

### ISSUE THREAD

**Issue by csevast** [AndreMiras/pycaw#10]
I would like to ask if I can use the method in the issue subject and how. I have in my application a slide control, which I want to make it to be changed if master control is changed outside of my application.

**Comment by csevast** [comment]
Hmmm, I tried already to do something but I have to confess that I'm not familiar in this kind of programming, the interfacing of Python with Windows APIs. It would be very helpful if you send me some reference links to read about it.

**Comment by AndreMiras** [comment]
Where got you stuck? The doc would be the official one: [IAudioEndpointVolumeCallback::OnNotify](https://docs.microsoft.com/en-us/windows/desktop/api/endpointvolume/nf-endpointvolume-iaudioendpointvolumecallback-onnotify) with some copy/paste/modify from the existing code base.
As silly as it seems, I'm not that familiar either, I've been running Linux only for the last 10 years :joy:  I actually made this project for a friend of mine and every-time I need to maintain it, I have to setup a Wndows VM.
Maybe you could share the piece of code you're struggling with and we could walk through it together, would that make sense?

**Comment by csevast** [comment]
I made something but it doesn't work.

[pycaw[20181220-01-csevast].zip](https://github.com/AndreMiras/pycaw/files/2698976/pycaw.20181220-01-csevast.zip)

**Comment by AndreMiras** [comment]
Kudos for trying. Next time you can also try with sharing a WIP pull request :wink: 
I'm pretty busy at the moment, but I'll definitely take a look when I have a minute
