### ISSUE TITLE
How do I mute a specific window

### ISSUE THREAD

**Issue by spookybear0** [AndreMiras/pycaw#22]
Title, would like to mute discord when getting far on geometry dash.

**Comment by TurboAnonym** [comment]
Its probably to late but maybe it will help someone ;)

```
from pycaw.pycaw import AudioUtilities
sessions = AudioUtilities.GetAllSessions()

for session in sessions:
    if session.Process and session.Process.name() == "Discord.exe":
        controll = session.SimpleAudioVolume
        controll.SetMute(True, None)  # use SetMute(False, None) to unmute
```

**Comment by AndreMiras** [comment]
https://github.com/AndreMiras/pycaw/blob/v20190904/examples/volume_by_process_example.py

**Comment by gitagogaming** [comment]
> Its probably to late but maybe it will help someone ;)
> 
> ```
> from pycaw.pycaw import AudioUtilities
> sessions = AudioUtilities.GetAllSessions()
> 
> for session in sessions:
>     if session.Process and session.Process.name() == "Discord.exe":
>         controll = session.SimpleAudioVolume
>         controll.SetMute(True, None)  # use SetMute(False, None) to unmute
> ```

discord loads two audio endpoints, and unfortunately this and any other method ive tried is unable to mute them both.. 
the first one that is muted by this command above is not the one that actually does anything worth while.. 

The 'second' discord device here is the one that needs changed.. 

wondering if anyone has found a fix for this?
![image](https://github.com/user-attachments/assets/db83daa4-db49-4b74-bd02-d86f837d13da)
