### ISSUE TITLE
PYTHON IDLE SUBPROCESS ERROR!! COULD NOT MAKE CONNECTION

### ISSUE THREAD

**Issue by 123456789123456789987654321123456789** [AndreMiras/pycaw#23]
I am unable to open idle and also on my vscode iam  unable to run python files.

WHAT I've tried :
I saw many videos and many sites they say "delete all new files created in python directory", BUT"" I'VE NO python FILES IN PYTHON DIRECTORY  ""

HELP!!!!!!!!!!!!!!!!!!!

**Comment by AndreMiras** [comment]
I'm not sure this is pycaw related, feel free to re-open providing details if you think it is
