### ISSUE TITLE
How to use SetChannelVolumeLevelScalar

### ISSUE THREAD

**Issue by McCrafterIV** [AndreMiras/pycaw#24]
I tried `volume.SetChannelVolumeLevelScalar(0, 20, None)` with 0 as the volume id and 20 as the volume precentage level. But this hasn't worked and I got he following Stacktrace:
```
Traceback (most recent call last):
  File "file.py", line 20, in <module>
    volume.SetChannelVolumeLevelScalar(0, 20, None)
_ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
```
I can't figure out how to use this function. The spare documentation also doesn't even mention it. I would use `SetMasterVolumeLevel` but I can't figure out how to calculate the value of a percentage value.

**Comment by lucatatas** [comment]
Hi!
SetMasterVolumeLevelScalar(level, None), where level is your desired volume level works just fine for me.

**Comment by AndreMiras** [comment]
Seems solved, feel free to re-open if not
