### ISSUE TITLE
Error when using pycaw with Ctypes

### ISSUE THREAD

**Issue by jliu83** [AndreMiras/pycaw#3]
Hi, I get the following error when using the function AudioUtilities.GetAllDevices().  Seems to be an issue with ctypes.  It works on my other machine, but this particular laptop does not like it.  Any ideas as to how to resolve this issue?

Running Windows10
Python 2.7.3 64 bit

error:
```
Traceback (most recent call last):
  File "mvol.py", line 13, in <module>
    devices = AudioUtilities.GetAllDevices()
  File "C:\python_27_amd64\files\lib\site-packages\pycaw\pycaw.py", line 701, in GetAllDevices
    devices.append(AudioUtilities.CreateDevice(dev))
  File "C:\python_27_amd64\files\lib\site-packages\pycaw\pycaw.py", line 673, in CreateDevice
    value = store.GetValue(pk)
_ctypes.COMError: (-536870389, None, (None, None, None, 0, None))
```

Here is the snippet of code that I am running:
```python
from ctypes import cast, POINTER
from comtypes import CLSCTX_ALL
from pycaw.pycaw import AudioUtilities, IAudioEndpointVolume
devices = AudioUtilities.GetSpeakers()
interface = devices.Activate(
    IAudioEndpointVolume._iid_, CLSCTX_ALL, None)
volume = cast(interface, POINTER(IAudioEndpointVolume))
print(volume.GetMute())
print(volume.GetMasterVolumeLevel())
print(volume.GetVolumeRange())
volume.SetMasterVolumeLevel(-20.0, None)

devices = AudioUtilities.GetAllDevices()
for d in devices:
  print(str(d) + " " + str(d.state))
```

Let me know if I can try something to test, or if you need additional info. 

Make sure to give enough information to help debugging your issue.
Here are some hints:

- current requirements (pip freeze)
- OS version
- architecture
- Python version
- pycaw version
- project files
- exact stacktrace / accurate error message
- and so on

**Comment by AndreMiras** [comment]
I've updated your formatting a little bit for readability.
Also next time you can provide me with a `pip freeze` output.
To get the actual error you can convert the error to the Windows hexadecimal error code.
```
>>> hex(0x100000000-536870389)
'0xe000020b'
```
So the actual error seems to be `0xE000020B`, dunno why comtypes doesn't return that instead, it would simplify debugging a lot.
Anyway this particular error seems to be related to a problem with your drivers. Please verify and come back to me.

**Comment by jliu83** [comment]
I've disabled my audio device, ran the script, then enabled it again.  It seems to have fixed the issue.  No idea why this manifested.  Thanks for looking into this.

**Comment by AndreMiras** [comment]
Glad it's fixed :)

**Comment by riti044** [comment]
<img width="1440" alt="Screen Shot 2021-11-08 at 9 19 40 PM" src="https://user-images.githubusercontent.com/93737621/140788519-6d401789-f80e-424f-b770-f9d07f7d8d3c.png">
hi cn someone pls tell. me how I cn fix this error

**Comment by riti044** [comment]
i hv no idea

**Comment by AndreMiras** [comment]
> <img alt="Screen Shot 2021-11-08 at 9 19 40 PM" width="1440" src="https://user-images.githubusercontent.com/93737621/140788519-6d401789-f80e-424f-b770-f9d07f7d8d3c.png">
> 
> hi cn someone pls tell. me how I cn fix this error

pycaw is Microsoft Windows only, it doesn't run on macOS or Linux

**Comment by riti044** [comment]
ah ok but i really want to use it :(

**Comment by riti044** [comment]
cn j pls pls pls pls pls make it for mac :(

**Comment by AndreMiras** [comment]
I wish I had a mac and time to do it. But there must be some equivalent in mac I imagine

**Comment by riti044** [comment]
ahh cn u pls tell me what it is
