### ISSUE TITLE
IChannelAudioVolume and IAudioStreamVolume interfaces support

### ISSUE THREAD

**Issue by grisov** [AndreMiras/pycaw#33]
Thank you for your much needed work on such a useful module!

Please, could you add support the IChannelAudioVolume and IAudioStreamVolume WASAPI interfaces support?

This would allow [to control the volume level of individual channels for running processes][1].
Thank you!

[1]: https://docs.microsoft.com/en-us/windows/win32/coreaudio/session-volume-controls

**Comment by AndreMiras** [comment]
Hi @grisov I don't have much time to add the new interface, but I would be happy to review a pull request that brings the support

**Comment by grisov** [comment]
ok, i understand.  

I will try to add these interfaces later.
