### ISSUE TITLE
Python IDLE subprocess startup error

### ISSUE THREAD

**Issue by Louie0807** [AndreMiras/pycaw#5]
Hi I'm learning Python. I get the error while trying to open IDLE Python:

"IDLE subprocess didn't make connection. Either IDLE can't start a subprocess or personal firewall software is blocking the connection."

Without closing the message, after a while, another error message:

"IDLE's subprocess can't connect to 127.0.0.1:53212.
Fatal OSError #10060: A connection attempt failed because the connected party did not properly
respond after a period of time or established connection failed because connected host has
failed to respond.
See the Startup failure section of the IDLE doc, online at
https://docs.python.org/3/library/idle.html#startup-failure"

What I've tried:

-Turning off virus software and firewall.
-Enable Telnet service.
-Complete uninstall Python and all its associated files like registry with Revo Uninstaller and install again.
-Tried install Anaconda3, then uninstalled.
-Tried installed 64bit Python first, then uninstalled, installed 32bit. Now remains with 32bit Python.

No luck from above. The IDLE doc don't seem to give me relevant solutions to my case.

I'm using Windows 8.1, any advice? I don't have much knowledge about networking, could it be a DNS issue?

**Comment by AndreMiras** [comment]
Hi @Louie0807, it doesn't seem to be a pycaw issue, perhaps you should ask on some IDLE related group?
