### ISSUE TITLE
Trouble installing pycaw from the Github Repo

### ISSUE THREAD

**Issue by meltyness** [AndreMiras/pycaw#54]
- OS version Windows 10 Home, 20H2
- architecture amd64
- Python version 3.9.7
- pycaw version ?? the repo
- exact stacktrace / accurate error message
After installing repo with pip, can't import pycaw.api, etc.

Anyways, the solution was as follows, in the setup.py:
`~from setuptools import setup, find_packages`
`      packages=find_packages(),`

problem solved!

Unfortunately I don't know the deltas on the python specs or what all the Travis CI stuff is supposed to do formally enough to tell if this is a proper solution or not, but it seems to make sense to me, I guess. Anyway, bye!

**Comment by AndreMiras** [comment]
Thanks for the report, this got fixed via #63
