### ISSUE TITLE
pycaw-comtypes issue

### ISSUE THREAD

**Issue by theseaofsilence** [AndreMiras/pycaw#55]
Hello All,

I am new to programming. I installed pycaw and comtypes also got installed with it. 

I am getting the below error in the comtypes/__init__.py file. Please help.

- exact stacktrace / accurate error message:
Traceback (most recent call last):
  File "C:/HandTrackingProject/VolumeHandControl.py", line 7, in <module>
    from comtypes import CLSCTX_ALL
  File "C:\HandTrackingProject\lib\site-packages\comtypes\__init__.py", line 375
    except COMError, err:
                   ^
SyntaxError: invalid syntax
-------------------------------------------
- OS version - Windows 10
- architecture - x64
- Python version - 3.8
- pycaw version - 20181226
- comtypes version - 1.1.10
-----------------------------------------------

**Comment by adiee5** [comment]
i have this problem too

**Comment by wqtb** [comment]
the same to you both

**Comment by theseaofsilence** [comment]
@adiee5 @wqtb please share if any of you find any solution.

**Comment by shukla1582** [comment]
has anyone found the solution pl help, same issue with my pycaw and com types also.

**Comment by Lambert12** [comment]
wait for solution

**Comment by AndreMiras** [comment]
This got solved by adding support for recent Python versions.
Try to install the latest version https://pypi.org/project/pycaw/20220416/
