### ISSUE TITLE
Windows Audio Callback Feature Request

### ISSUE THREAD

**Issue by gitagogaming** [AndreMiras/pycaw#60]
I was wondering if it would be possible to add, or if anyone has implemented a callback? 

https://docs.microsoft.com/en-us/windows/win32/api/endpointvolume/nn-endpointvolume-iaudioendpointvolumecallback

**Comment by gitagogaming** [comment]
I should of dug a bit deeper.. didnt see the DEV branch. sorry!

**Comment by AndreMiras** [comment]
Well I should release more often...
I should try to make one soon I guess
