### ISSUE TITLE
COMError when using SetMasterVolume

### ISSUE THREAD

**Issue by Evolution0** [AndreMiras/pycaw#7]
Having an issue using `SetMasterVolume()`

Windows 10 x64, Python 3.6.3, PyCaw 20160929

Traceback:
```
Traceback (most recent call last):
  File "C:/Users/Anthony/PycharmProjects/DiscordGlobalVolume/main.py", line 33, in <module>
    main()
  File "C:/Users/Anthony/PycharmProjects/DiscordGlobalVolume/main.py", line 26, in main
    keyboard.add_hotkey('ctrl+u', volume_adjust(interface, 0.1))
  File "C:/Users/Anthony/PycharmProjects/DiscordGlobalVolume/main.py", line 15, in volume_adjust
    interface.SetMasterVolume(updated_volume, None)
_ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
```

It seems to not like being passed `None` where it expects an LP_GUID instance yet this is what I see being done in all the examples.

For additional context I'm fetching all the sessions with `AudioUtilities.GetAllSessions()`, looping through those till I find the one I want then doing `interface = session.SimpleAudioVolume` and passing the interface to my function which adjusts it either up or down based on a hotkey.

**Comment by AndreMiras** [comment]
Hi @Evolution0, thank you so much for the bug report.
Could you share a small code snippet that makes it possible to reproduce it?
Can you also try it on develop branch?
```
pip install https://github.com/AndreMiras/pycaw/archive/develop.zip
```

**Comment by Evolution0** [comment]
Seems to not happen in the develop branch 😸 

Here is the code that caused it in the stable branch if its of any interest:
```python
import keyboard
from pycaw.pycaw import AudioUtilities


target_process = 'Discord.exe'


def main():
    def volume_adjust(volume, amount):
        print(volume)
        current_volume = volume.GetMasterVolume()
        updated_volume = current_volume + amount
        volume.SetMasterVolume(updated_volume, None)
        print(volume.GetMasterVolume())

    sessions = AudioUtilities.GetAllSessions()
    for session in sessions:
        if session.Process and session.Process.name() == target_process:
            break

    if session:
        volume = session.SimpleAudioVolume
        # Register our hotkeys
        keyboard.add_hotkey('ctrl+u', volume_adjust(volume, 0.1))
        keyboard.add_hotkey('ctrl+d', volume_adjust(volume, -0.1))
    else:
        quit()


if __name__ == '__main__':
    main()

```

**Comment by AndreMiras** [comment]
Sorry it's been a while since I couldn't touch a Windows laptop to give it a try.
The good news is I could reproduce it, hopefully I can work on it pretty soon.
In the meantime @Evolution0 did you find a way around?

**Comment by AndreMiras** [comment]
OK this was because it gets outside the range, so you need to make sure it's within the range.
So replace this line:
```python
updated_volume = current_volume + amount
```
By that one:
```python
updated_volume = min(1.0, max(0.0, updated_volume))
```
See official documentation https://docs.microsoft.com/en-us/windows/desktop/api/audioclient/nf-audioclient-isimpleaudiovolume-setmastervolume

Feel free to re-open if it's still an issue.
